services:
  - type: web
    name: ailingo-backend
    env: node
    buildCommand: "npm install && npm run build:server"
    startCommand: "npm run start:server"
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: data-db
      mountPath: /opt/render/project/src/data
      sizeGB: 1
